services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    ports:
      - "127.0.0.1:4001:4001"  # Swarm port for peer connections
      - "127.0.0.1:5001:5001"  # API port for local interactions
      - "127.0.0.1:8080:8080"  # Gateway port for serving content
    volumes:
      - ./ipfs_data:/data/ipfs
      - ./scripts/ipfs_entrypoint.sh:/usr/local/bin/ipfs_entrypoint.sh
    entrypoint: ["/usr/local/bin/ipfs_entrypoint.sh"]
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 5s
      timeout: 5s
      retries: 9
      start_period: 5s